### ISSUE TITLE
Update Harmony to use Steam dependency

### ISSUE THREAD

**Issue by n-fisher** [bcooper94/ColorCodedMoodBar#4]
## Issue
Harmony is now its own Steam mod to fix a 1.1 dependency bug: https://www.reddit.com/r/RimWorld/comments/fbnm45/harmony_the_full_story/

## Fix
Remove `0Harmony.dll` and add this tag to your About.xml: https://github.com/pardeike/HarmonyRimWorld/blob/master/README.md

**Comment by bcooper94** [comment]
Fixed with https://github.com/bcooper94/ColorCodedMoodBar/commit/83e77b7f5783dece0aaf4c8ea466acf30ef48fe3. The Harmony mod is now required to run this mod.
