### ISSUE TITLE
Published a fork of this

### ISSUE THREAD

**Issue by emipa606** [bcooper94/ColorCodedMoodBar#7]
Would like to inform about a fork of this mod that I published
https://steamcommunity.com/sharedfiles/filedetails/?id=2434621881
https://github.com/emipa606/MuzzyUtils

Hope this is okay!

**Comment by EmmanuelMess** [comment]
> Would like to inform about a fork of this mod that I published
> [steamcommunity.com/sharedfiles/filedetails/?id=2434621881](https://steamcommunity.com/sharedfiles/filedetails/?id=2434621881)
> [emipa606/MuzzyUtils](https://github.com/emipa606/MuzzyUtils)
> 
> Hope this is okay!

Please allow issues in your fork.

**Comment by emipa606** [comment]
Strange, never had to turn that on specifically. Should be on now
